# Build Stage
FROM rust:latest AS build

WORKDIR /app

# Copy only the Cargo.toml and Cargo.lock to cache dependencies
COPY Cargo.toml Cargo.lock ./

# Build the dependencies
RUN cargo build --release

# Copy the source code
COPY app .
RUN cd app
# Build the application
RUN cargo build --release

# Final Stage
FROM debian:buster-slim

WORKDIR /app

# Copy only the compiled binary from the build stage
COPY --from=build /app/target/release/your_grpc_server_app .

# Expose the gRPC server port
EXPOSE 50051

# Start the application
CMD ["./your_grpc_server_app"]
